Repository ember-cli/ember-fetch, pull requests merged in 2018-12, with the labels that each got.

#182 TravisCI: Remove deprecated `sudo: false` option
  .travis.yml
  ember-fetch-6.1.1.tgz
Labels: internal

#183 Remove mistakenly committed release tarball
  ember-fetch-6.1.1.tgz
Labels: internal

#171 Setup addon tests
  .eslintignore
  .travis.yml
  package.json
  test/fastboot-build-test.js
  test/fastboot-test.js
  test/fixtures/dummy/app/app.js
  test/fixtures/dummy/app/components/.gitkeep
  test/fixtures/dummy/app/controllers/.gitkeep
  test/fixtures/dummy/app/helpers/.gitkeep
  test/fixtures/dummy/app/index.html
  test/fixtures/dummy/app/models/.gitkeep
  test/fixtures/dummy/app/resolver.js
  test/fixtures/dummy/app/router.js
  test/fixtures/dummy/app/routes/.gitkeep
  test/fixtures/dummy/app/routes/index.js
  test/fixtures/dummy/app/styles/app.css
  test/fixtures/dummy/app/templates/application.hbs
  test/fixtures/dummy/app/templates/components/.gitkeep
  test/fixtures/dummy/app/templates/index.hbs
  test/fixtures/dummy/config/environment.js
  test/fixtures/dummy/config/targets.js
  test/fixtures/dummy/ember-cli-build.js
  test/fixtures/dummy/public/omg.json
  test/fixtures/dummy/public/robots.txt
  yarn.lock
Labels: internal

#174 Support POST body of all valid types
  addon/utils/mung-options-for-fetch.js
  tests/unit/utils/mung-options-for-fetch-test.js
Labels: enhancement

#177 Only set default Content-Type header in adapter mixin
  addon/mixins/adapter-fetch.js
  addon/utils/mung-options-for-fetch.js
  tests/unit/mixins/adapter-fetch-test.js
  tests/unit/utils/mung-options-for-fetch-test.js
Labels: bug

#173 Do not include polyfill if browser targets don't need it
  README.md
  assets/browser-fetch.js.t
  index.js
  package.json
  test/browsers-target-test.js
  yarn.lock
Labels: enhancement
