Repository ember-cli/ember-fetch, pull requests merged in 2020-03, with the labels that each got.

#447 Remove ember-fetch/mixins/adapter-fetch ember-fetch/ajax, drop node 8
  .travis.yml
  README.md
  addon/ajax.ts
  addon/mixins/adapter-fetch.ts
  appveyor.yml
  assets/browser-fetch.js.t
  package.json
  public/fetch-fastboot.js
  tests/acceptance/error-test.js
  tests/acceptance/root-test.js
  tests/dummy/app/routes/index.js
  tests/dummy/app/templates/index.hbs
  tests/unit/mixins/adapter-fetch-test.js
Labels: breaking

#474 Upgrade dependencies
  package.json
  yarn.lock
Labels: dependencies

#479 Bump broccoli-merge-trees
  package.json
  yarn.lock
Labels: dependencies, internal
